import { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Message = { id: string; role: "child" | "assistant"; content: string; time: string; state?: "safe" | "guided"; source?: "local" | "llm" };
type Conversation = { id: string; title: string; topic: string; updated: string; messages: Message[] };
type LlmStatus = { available: boolean; enabledDefault: boolean; model?: string; mode: string };
type AdminUser = { id: string; display_name: string; email: string | null; username: string; safety_profile: string };
type SafetyProfile = { id: string; name: string; age_band: string; reading_level: string; prompt_content: string; input_thresholds: Record<string, number>; output_thresholds: Record<string, number> };

const welcome: Message = { id: "welcome", role: "assistant", content: "Hi Maya! I'm here to help you learn. What would you like to explore today?", time: "Now", state: "safe" };
const starterConversations: Conversation[] = [{ id: "space", title: "Why do stars twinkle?", topic: "Space", updated: "Today", messages: [welcome] }, { id: "plants", title: "How plants drink water", topic: "Science", updated: "Yesterday", messages: [welcome] }];
const apiBase = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";
const tokenKey = "brightpath.adminToken";
const profileNames = ["Less than 10", "10-13", "13-15", "15-17"];

function App() {
  const [conversations, setConversations] = useState(starterConversations);
  const [activeId, setActiveId] = useState("space");
  const [draft, setDraft] = useState("");
  const [waiting, setWaiting] = useState(false);
  const [adminOpen, setAdminOpen] = useState(false);
  const [llm, setLlm] = useState<LlmStatus>({ available: false, enabledDefault: false, mode: "safe-local-demo" });
  const [useLlm, setUseLlm] = useState(false);
  const active = conversations.find((conversation) => conversation.id === activeId) ?? conversations[0];
  const filtered = useMemo(() => conversations, [conversations]);

  useEffect(() => { fetch(`${apiBase}/health`).then((response) => response.json()).then((data) => { setLlm({ available: Boolean(data.llm_available), enabledDefault: Boolean(data.llm_enabled_default), model: data.model || undefined, mode: data.mode }); setUseLlm(Boolean(data.llm_available && data.llm_enabled_default)); }).catch(() => undefined); }, []);
  function startConversation() { const id = crypto.randomUUID(); setConversations((items) => [{ id, title: "New question", topic: "Learning", updated: "Now", messages: [welcome] }, ...items]); setActiveId(id); }
  async function send(event: FormEvent) {
    event.preventDefault(); const content = draft.trim(); if (!content || waiting) return;
    const childMessage: Message = { id: crypto.randomUUID(), role: "child", content, time: "Now" };
    setConversations((items) => items.map((conversation) => conversation.id === active.id ? { ...conversation, title: conversation.title === "New question" ? content.slice(0, 42) : conversation.title, messages: [...conversation.messages, childMessage] } : conversation)); setDraft(""); setWaiting(true);
    try { const response = await fetch(`${apiBase}/v1/chat/messages`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": childMessage.id }, body: JSON.stringify({ conversation_id: active.id, content, use_llm: useLlm }) }); if (!response.ok) throw new Error(); const data = await response.json(); const assistantMessage: Message = { id: data.id, role: "assistant", content: data.content, time: "Now", state: data.safety_state, source: data.source }; setConversations((items) => items.map((conversation) => conversation.id === active.id ? { ...conversation, topic: data.topic || conversation.topic, messages: [...conversation.messages, assistantMessage] } : conversation)); } catch { const fallback: Message = { id: crypto.randomUUID(), role: "assistant", content: "I need a moment before I can answer safely. Please try again soon, or ask a trusted adult to help.", time: "Now", state: "guided" }; setConversations((items) => items.map((conversation) => conversation.id === active.id ? { ...conversation, messages: [...conversation.messages, fallback] } : conversation)); } finally { setWaiting(false); }
  }
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">*</span><span>BrightPath</span></div><button className="new-chat" onClick={startConversation}>+ New chat</button><p className="side-label">YOUR LEARNING</p><nav>{filtered.map((conversation) => <button key={conversation.id} onClick={() => setActiveId(conversation.id)} className={`conversation-link ${activeId === conversation.id ? "selected" : ""}`}><span className="conversation-title">{conversation.title}</span><span>{conversation.topic}</span></button>)}</nav><div className="sidebar-footer"><button className="admin-link" onClick={() => setAdminOpen(true)}>Admin settings</button></div></aside><section className="chat"><header className="topbar"><div><p className="eyebrow">LEARNING SPACE</p><h1>{active.title}</h1></div><div className="topbar-actions"><label className="llm-toggle"><input type="checkbox" checked={useLlm} disabled={!llm.available || waiting} onChange={(event) => setUseLlm(event.target.checked)} /><span>{useLlm ? "AI answers on" : "AI answers off"}</span></label><div className="safety-badge">Safe learning space</div></div></header><div className="messages">{active.messages.map((message) => <article key={message.id} className={`message ${message.role}`}><div className="avatar">{message.role === "child" ? "M" : "*"}</div><div><div className="bubble">{message.content}</div><div className="message-meta">{message.time}{message.source === "llm" && " · AI answer"}</div></div></article>)}</div><form className="composer" onSubmit={send}><textarea value={draft} maxLength={1200} onChange={(event) => setDraft(event.target.value)} placeholder="Ask anything you're curious about..." /><button disabled={!draft.trim() || waiting}>{waiting ? "Checking..." : "Ask"}</button></form></section>{adminOpen && <AdminPanel onClose={() => setAdminOpen(false)} />}</main>;
}

function AdminPanel({ onClose }: { onClose: () => void }) {
  const [token, setToken] = useState(() => sessionStorage.getItem(tokenKey) || ""); const [username, setUsername] = useState("admin"); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [tab, setTab] = useState<"users" | "profiles">("users"); const [users, setUsers] = useState<AdminUser[]>([]); const [profiles, setProfiles] = useState<SafetyProfile[]>([]);
  async function load() { const headers = { Authorization: `Bearer ${token}` }; const [usersResponse, profilesResponse] = await Promise.all([fetch(`${apiBase}/v1/admin/users`, { headers }), fetch(`${apiBase}/v1/admin/safety-profiles`, { headers })]); if (!usersResponse.ok || !profilesResponse.ok) throw new Error("Your admin session has expired. Please sign in again."); setUsers(await usersResponse.json()); setProfiles(await profilesResponse.json()); }
  useEffect(() => { if (token) load().catch((reason) => { setError(reason.message); sessionStorage.removeItem(tokenKey); setToken(""); }); }, [token]);
  async function login(event: FormEvent) { event.preventDefault(); setError(""); const response = await fetch(`${apiBase}/v1/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); if (!response.ok) { setError("Invalid administrator username or password."); return; } const data = await response.json(); sessionStorage.setItem(tokenKey, data.token); setToken(data.token); setPassword(""); }
  if (!token) return <div className="modal-backdrop"><section className="admin-login"><button className="icon-button close-admin" onClick={onClose}>×</button><p className="eyebrow">ADMIN AREA</p><h2>Sign in</h2><form onSubmit={login}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></label>{error && <p className="form-error">{error}</p>}<button className="publish">Sign in</button></form></section></div>;
  return <div className="modal-backdrop"><section className="admin-panel"><header><div><p className="eyebrow">ADMIN AREA</p><h2>BrightPath administration</h2></div><button className="icon-button" onClick={onClose}>×</button></header><div className="admin-layout"><nav><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}>User management</button><button className={tab === "profiles" ? "active" : ""} onClick={() => setTab("profiles")}>Safety profiles</button><button onClick={() => { sessionStorage.removeItem(tokenKey); setToken(""); }}>Sign out</button></nav><div className="admin-content">{error && <p className="form-error">{error}</p>}{tab === "users" ? <UserManagement token={token} users={users} profiles={profiles} onSaved={load} onError={setError} /> : <ProfileManagement token={token} profiles={profiles} onSaved={load} onError={setError} />}</div></div></section></div>;
}

function UserManagement({ token, users, profiles, onSaved, onError }: { token: string; users: AdminUser[]; profiles: SafetyProfile[]; onSaved: () => Promise<void>; onError: (message: string) => void }) {
  const blank = { name: "", email: "", username: "", password: "", safety_profile: "Less than 10" }; const [form, setForm] = useState(blank); const [editing, setEditing] = useState<AdminUser | null>(null); const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  function edit(user: AdminUser) { setEditing(user); setForm({ name: user.display_name, email: user.email || "", username: user.username, password: "", safety_profile: user.safety_profile }); }
  async function submit(event: FormEvent) { event.preventDefault(); onError(""); const payload = { ...form, email: form.email || null, password: form.password || undefined }; const url = editing ? `${apiBase}/v1/admin/users/${editing.id}` : `${apiBase}/v1/admin/users`; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(payload) }); if (!response.ok) { onError((await response.json()).detail || "Unable to save user."); return; } setEditing(null); setForm(blank); await onSaved(); }
  return <><h3>User management</h3><p className="muted">User IDs are generated internally and are not displayed here.</p><form className="admin-form" onSubmit={submit}><label>Name<input value={form.name} onChange={(event) => update("name", event.target.value)} required /></label><label>Email ID (optional)<input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label>Username<input value={form.username} onChange={(event) => update("username", event.target.value)} required /></label><label>{editing ? "New password (leave blank to keep current)" : "Password"}<input type="password" value={form.password} onChange={(event) => update("password", event.target.value)} required={!editing} minLength={8} /></label><label>Safety profile<select value={form.safety_profile} onChange={(event) => update("safety_profile", event.target.value)}>{profiles.map((profile) => <option key={profile.id} value={profile.name}>{profile.name}</option>)}</select></label><div className="form-actions"><button className="publish">{editing ? "Update user" : "Add user"}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</button>}</div></form><table><thead><tr><th>Name</th><th>Email</th><th>Username</th><th>Profile</th><th></th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.display_name}</td><td>{user.email || "—"}</td><td>{user.username}</td><td>{user.safety_profile}</td><td><button className="table-button" onClick={() => edit(user)}>Edit</button></td></tr>)}</tbody></table></>;
}

function ProfileManagement({ token, profiles, onSaved, onError }: { token: string; profiles: SafetyProfile[]; onSaved: () => Promise<void>; onError: (message: string) => void }) {
  const [name, setName] = useState("Less than 10"); const profile = profiles.find((item) => item.name === name) || profiles[0]; const [draft, setDraft] = useState<SafetyProfile | null>(null); useEffect(() => { if (profile) setDraft(JSON.parse(JSON.stringify(profile))); }, [profile]); if (!draft) return null;
  const setScore = (kind: "input_thresholds" | "output_thresholds", category: string, value: string) => setDraft((current) => current ? { ...current, [kind]: { ...current[kind], [category]: Number(value) } } : current);
  async function save() { if (!draft) return; onError(""); const response = await fetch(`${apiBase}/v1/admin/safety-profiles/${encodeURIComponent(draft.name)}`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ prompt_content: draft.prompt_content, input_thresholds: draft.input_thresholds, output_thresholds: draft.output_thresholds }) }); if (!response.ok) { onError((await response.json()).detail || "Unable to save profile."); return; } await onSaved(); }
  const categories = Object.keys(draft.input_thresholds); return <><h3>Safety profiles</h3><label className="profile-select">Profile<select value={name} onChange={(event) => setName(event.target.value)}>{profileNames.map((profileName) => <option key={profileName}>{profileName}</option>)}</select></label><p className="muted">Age band: {draft.age_band} · Reading level: {draft.reading_level}</p><label className="prompt-editor">LLM prompt<textarea value={draft.prompt_content} onChange={(event) => setDraft({ ...draft, prompt_content: event.target.value })} /></label><h3>Moderation score maximums</h3><table><thead><tr><th>Category</th><th>Input</th><th>Output</th></tr></thead><tbody>{categories.map((category) => <tr key={category}><td>{category}</td><td><input className="score-input" type="number" min="0" max="1" step="0.01" value={draft.input_thresholds[category]} onChange={(event) => setScore("input_thresholds", category, event.target.value)} /></td><td><input className="score-input" type="number" min="0" max="1" step="0.01" value={draft.output_thresholds[category]} onChange={(event) => setScore("output_thresholds", category, event.target.value)} /></td></tr>)}</tbody></table><button className="publish" onClick={save}>Save profile</button></>;
}

createRoot(document.getElementById("root")!).render(<App />);
